name: anki-casept
version: '2.1.0a12'
summary: Friendly, intelligent flash cards. This is an unofficial snap. 
description: |
  Anki is a program which makes remembering things easy.
  Because it's a lot more efficient than traditional study methods,
  you can either greatly decrease your time spent studying, or greatly increase the amount you learn.

  Anyone who needs to remember things in their daily life can benefit from Anki.
  Since it is content-agnostic and supports images, audio, videos
  and scientific markup (via LaTeX), the possibilities are endless.


grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict


apps:
  anki:
    command: desktop-launch $SNAP/bin/python-wrapper $SNAP/usr/local/bin/anki
    plugs: [network, x11, opengl, pulseaudio]


parts:
  depends:
    plugin: python
    python-version: python3
    python-packages: [send2trash]
    stage-packages:
      - python3
      - python3-pyqt5
      - python3-pyqt5.qtwebengine
      - lame
      - libportaudio2
      - mplayer
      - libpulse0
      - libgl1-mesa-dri
      - python3-bs4
      - python3-httplib2
      - python3-pyaudio
      - python3-requests

    build-packages:
      - pyqt5-dev-tools
      - python3-pip
      - build-essential
      - portaudio19-dev
      - xdg-utils

  anki:
    plugin: make 
    source: https://apps.ankiweb.net/downloads/alpha/alpha12/anki-2.1.0a12-source.tgz
    prepare: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/local/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/man/man1/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications/
    after: [depends, desktop-qt5]

  wrapper:
    plugin: copy
    files:
      python-wrapper: bin/python-wrapper
